// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.zjut.DataFormat;

public final class HeartRspInfo {
  private HeartRspInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeartRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 head = 1;
    boolean hasHead();
    int getHead();
    
    // required int32 ad_id = 2;
    boolean hasAdId();
    int getAdId();
    
    // required string path = 3;
    boolean hasPath();
    String getPath();
    
    // required string name = 4;
    boolean hasName();
    String getName();
    
    // required string delTime = 5;
    boolean hasDelTime();
    String getDelTime();
    
    // required string end = 6;
    boolean hasEnd();
    String getEnd();
  }
  public static final class HeartRsp extends
      com.google.protobuf.GeneratedMessage
      implements HeartRspOrBuilder {
    // Use HeartRsp.newBuilder() to construct.
    private HeartRsp(Builder builder) {
      super(builder);
    }
    private HeartRsp(boolean noInit) {}
    
    private static final HeartRsp defaultInstance;
    public static HeartRsp getDefaultInstance() {
      return defaultInstance;
    }
    
    public HeartRsp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zjut.DataFormat.HeartRspInfo.internal_static_HeartRsp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zjut.DataFormat.HeartRspInfo.internal_static_HeartRsp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 head = 1;
    public static final int HEAD_FIELD_NUMBER = 1;
    private int head_;
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getHead() {
      return head_;
    }
    
    // required int32 ad_id = 2;
    public static final int AD_ID_FIELD_NUMBER = 2;
    private int adId_;
    public boolean hasAdId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getAdId() {
      return adId_;
    }
    
    // required string path = 3;
    public static final int PATH_FIELD_NUMBER = 3;
    private java.lang.Object path_;
    public boolean hasPath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          path_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string delTime = 5;
    public static final int DELTIME_FIELD_NUMBER = 5;
    private java.lang.Object delTime_;
    public boolean hasDelTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getDelTime() {
      java.lang.Object ref = delTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          delTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDelTimeBytes() {
      java.lang.Object ref = delTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        delTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string end = 6;
    public static final int END_FIELD_NUMBER = 6;
    private java.lang.Object end_;
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getEnd() {
      java.lang.Object ref = end_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          end_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEndBytes() {
      java.lang.Object ref = end_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        end_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      head_ = 0;
      adId_ = 0;
      path_ = "";
      name_ = "";
      delTime_ = "";
      end_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDelTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, adId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDelTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getEndBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, adId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDelTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getEndBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.zjut.DataFormat.HeartRspInfo.HeartRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zjut.DataFormat.HeartRspInfo.HeartRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zjut.DataFormat.HeartRspInfo.HeartRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zjut.DataFormat.HeartRspInfo.internal_static_HeartRsp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zjut.DataFormat.HeartRspInfo.internal_static_HeartRsp_fieldAccessorTable;
      }
      
      // Construct using com.zjut.DataFormat.HeartRspInfo.HeartRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        head_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        adId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        delTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        end_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zjut.DataFormat.HeartRspInfo.HeartRsp.getDescriptor();
      }
      
      public com.zjut.DataFormat.HeartRspInfo.HeartRsp getDefaultInstanceForType() {
        return com.zjut.DataFormat.HeartRspInfo.HeartRsp.getDefaultInstance();
      }
      
      public com.zjut.DataFormat.HeartRspInfo.HeartRsp build() {
        com.zjut.DataFormat.HeartRspInfo.HeartRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.zjut.DataFormat.HeartRspInfo.HeartRsp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.zjut.DataFormat.HeartRspInfo.HeartRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.zjut.DataFormat.HeartRspInfo.HeartRsp buildPartial() {
        com.zjut.DataFormat.HeartRspInfo.HeartRsp result = new com.zjut.DataFormat.HeartRspInfo.HeartRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.head_ = head_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.adId_ = adId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.delTime_ = delTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.end_ = end_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zjut.DataFormat.HeartRspInfo.HeartRsp) {
          return mergeFrom((com.zjut.DataFormat.HeartRspInfo.HeartRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.zjut.DataFormat.HeartRspInfo.HeartRsp other) {
        if (other == com.zjut.DataFormat.HeartRspInfo.HeartRsp.getDefaultInstance()) return this;
        if (other.hasHead()) {
          setHead(other.getHead());
        }
        if (other.hasAdId()) {
          setAdId(other.getAdId());
        }
        if (other.hasPath()) {
          setPath(other.getPath());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDelTime()) {
          setDelTime(other.getDelTime());
        }
        if (other.hasEnd()) {
          setEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHead()) {
          
          return false;
        }
        if (!hasAdId()) {
          
          return false;
        }
        if (!hasPath()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasDelTime()) {
          
          return false;
        }
        if (!hasEnd()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              head_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              adId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              path_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              delTime_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              end_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 head = 1;
      private int head_ ;
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getHead() {
        return head_;
      }
      public Builder setHead(int value) {
        bitField0_ |= 0x00000001;
        head_ = value;
        onChanged();
        return this;
      }
      public Builder clearHead() {
        bitField0_ = (bitField0_ & ~0x00000001);
        head_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 ad_id = 2;
      private int adId_ ;
      public boolean hasAdId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getAdId() {
        return adId_;
      }
      public Builder setAdId(int value) {
        bitField0_ |= 0x00000002;
        adId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAdId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        adId_ = 0;
        onChanged();
        return this;
      }
      
      // required string path = 3;
      private java.lang.Object path_ = "";
      public boolean hasPath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
        return this;
      }
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      void setPath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
      }
      
      // required string name = 4;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
      }
      
      // required string delTime = 5;
      private java.lang.Object delTime_ = "";
      public boolean hasDelTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getDelTime() {
        java.lang.Object ref = delTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          delTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDelTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        delTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearDelTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        delTime_ = getDefaultInstance().getDelTime();
        onChanged();
        return this;
      }
      void setDelTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        delTime_ = value;
        onChanged();
      }
      
      // required string end = 6;
      private java.lang.Object end_ = "";
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getEnd() {
        java.lang.Object ref = end_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          end_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEnd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        end_ = value;
        onChanged();
        return this;
      }
      public Builder clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000020);
        end_ = getDefaultInstance().getEnd();
        onChanged();
        return this;
      }
      void setEnd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        end_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:HeartRsp)
    }
    
    static {
      defaultInstance = new HeartRsp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HeartRsp)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartRsp_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"a\n\010HeartRsp\022\014\n\004head\030\001 \002(\005\022\r" +
      "\n\005ad_id\030\002 \002(\005\022\014\n\004path\030\003 \002(\t\022\014\n\004name\030\004 \002(" +
      "\t\022\017\n\007delTime\030\005 \002(\t\022\013\n\003end\030\006 \002(\tB#\n\023com.z" +
      "jut.DataFormatB\014HeartRspInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HeartRsp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HeartRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HeartRsp_descriptor,
              new java.lang.String[] { "Head", "AdId", "Path", "Name", "DelTime", "End", },
              com.zjut.DataFormat.HeartRspInfo.HeartRsp.class,
              com.zjut.DataFormat.HeartRspInfo.HeartRsp.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
